### ISSUE TITLE
Only Global API Key?

### ISSUE THREAD

**Issue by BitesizedLion** [ansleehk/Cloudflare-KV-Driver#1]
Why is this only useable with global API keys, unless it's something that Cloudflare forces, I don't see the reason for it?

Regular API Tokens are much better since you can heavily restrict the permissions on those.

**Comment by meow-developer** [comment]
The reason for this is that some Worker Kv functions cannot be accessed through the API token when I write this driver. My original design is to use the API token way to do the authentication but I found out the permission sets offered by Cloudflare do not have enough permission to access some functions. If memory serves, creating a namespace is not allowed through API token. I understand this is not ideal. I will check whether those functions can be accessed through API token now.
